name: Deploy Backend to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate to Google Cloud
        if: ${{ secrets.GCP_SA_KEY != '' }}
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Build and push Docker image
        if: ${{ secrets.GCP_SA_KEY != '' }}
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/nika-dashboard-backend:latest backend

      - name: Deploy to Cloud Run
        if: ${{ secrets.GCP_SA_KEY != '' }}
        run: |
          gcloud run deploy nika-dashboard-backend --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/nika-dashboard-backend:latest --platform managed --region us-central1 --allow-unauthenticated
